### PR TITLE
bugfix  issue #14 - icelat diagnostics in asymetric EBM 

### PR DESCRIPTION
**Pull request by m-kreuzer**
changed the  `find_icelines` method of `climlab.surface.albedo.Iceline` class to determine ice edge latitude correctly - also if not symmetric.

This plot is produced by following model (and corrected code): `climlab.EBM_seasonal(ai=0.6, Tf=-15)`
fix_icelat_ebm_seasonal

### CODE REVIEW

**Comment by rabernat** [comment]
@m-kreuzer it would be great if you could add some tests for the ice edge diagnostic to this PR

**Comment by m-kreuzer** [comment]
@rabernat I'll have a look at it. Thanks for raising the test issue. I didn't find time yet to look into the testing framework.

**Comment by rabernat** [comment]
There don't appear to be any tests of the EBM at all yet.

I would use the ``gray_radiation``  tests
https://github.com/brian-rose/climlab/blob/master/climlab/tests/test_grey_radiation.py
as a template for a file called climlab/tests/test_ebm.py

Then modify it to test some of the basic functionality defined in the EBM notebook:
https://github.com/brian-rose/climlab/blob/master/courseware/Snowball%20Earth%20in%20the%20EBM.ipynb

You can run the tests locally by typing ``py.test -v`` in the base directory.

**Comment by brian-rose** [comment]
@rabernat Thanks for pointing this out, yes, we need to work on developing the test suite.

**Comment by brian-rose** [comment]
I just added a new `test_ebm.py` to the test suite. It checks some basic results from seasonal EBMs (no interactive ice) and annual mean EBMs (with interactive ice). @m-kreuzer that would be a great place to add a test for asymmetric ice edges.

**Pull request merged**
