### PR TITLE
dependencies in setup.py

### PR DESCRIPTION
**Pull request by krachyon**
Adding dependencies to setup.py and adding an error message if numpy is not already installed, as it's used before the install_requires can trigger. This isn't really optimal, but I'm not 100% sure how this issue would be solved properly. With a requirements file maybe?

### CODE REVIEW

**Comment by krachyon** [comment]
ok, so with the pyproject.toml numpy should be installed before setup.py is run.

**Comment by brian-rose** [comment]
Can you explain more precisely what problem or what use case you're trying to solve? How are you building climlab?

I rely on conda environments for building and running climlab, and there are platform specific `requirements*.yml` files in the `ci` directory. 

The developer documentation is kind of out of date unfortunately, but you can find a simple build procedure outlined in #75

**Comment by krachyon** [comment]
Well basically just make it so that `pip install climlab` neither errors if numpy is not present nor is missing dependencies after install. Seems to mostly work, but I wasn't aware of the issues relating to Fortran compilation, but at least on linux with gfortran available there are no build errors...

**Comment by brian-rose** [comment]
I see, so this relates closely to #75. 

I'm not sure at the moment why many of the test builds have failed here. May or may not be related to changed in your PR.

**Comment by krachyon** [comment]
Seems to at least not complain about the setup process, I'm still trying to figure out if I can get the Fortran compilation/installation to work properly, maybe it's related to that...

**Comment by brian-rose** [comment]
I just checked, and it looks like the same errors are happening on the master branch:
https://travis-ci.org/brian-rose/climlab/builds/553828075

Likely there is a new problem that's been triggered by updates to some of the upstream dependencies, since I haven't tried building in a few months. Will need to be fixed obviously.

I'll open a new issue about this.

**Comment by krachyon** [comment]
Ok, I still found a brainfart relating to the parameter names in setup.py. About the Fortran thing: 
when I run `python setup.py build` it compiles all the Fortran submodules and seems to properly install them with `python setup.py install` except cam3 (which creates a warning during import of climlab). There is a built `build/lib.linux-x86_64-3.7/climlab/radiation/cam3/_cam3.cpython-37m-x86_64-linux-gnu.so` but apparently it's not properly installed.

Seems to me though that most of it is mostly handled by the numpy.distutils magic, so maybe it's just a little tweak to make the `pip install` fully functional...

**Comment by brian-rose** [comment]
You're probably right, but I first need to fix whatever has gone wrong that's causing builds on the master branch to fail (#113), so we can have working tests again.

It may be a little while before I can find the time to look at that.

**Comment by brian-rose** [comment]
@krachyon please merge the latest master into your branch, that should get the test builds working properly again.

**Comment by brian-rose** [comment]
Dang it, I think I screwed this up by merging after I'd already updated setup.py with a newer version number, so your changes got discarded.

@krachyon would you mind reopening a new PR off of the latest master, and I'll get it merged before I break things again. Thanks.

**Comment by krachyon** [comment]
Hi,
looks to me like the changes are still there, i.e `install_requires` and the `try except` to check for the compiler. I merged the master into my fork again and there's no difference between the branches anymore.

**Comment by brian-rose** [comment]
Argh, you are right. Sorry. I think I was looking at a stale page. 

Thanks for your contribution!

**Pull request merged**
