### PR TITLE
Spectral OLR tutorial notebook for RRTMG_LW

### LINKED ISSUE #147: Add a tutorial on spectral bands in RRTMG
Following the success of @AndrewWilliams3142 in implementing TOA spectral band output for RRTMG_LW, it would be great to get a tutorial notebook showing off how (and why) to use this feature. 

We can integrate the notebook into the climlab docs [here](https://climlab.readthedocs.io/en/latest/tutorial.html). To do this, we just put a new notebook into the [courseware directory](https://github.com/brian-rose/climlab/tree/main/courseware) at the root level of the repo, and then add a link on [this page in the doc source](https://github.com/brian-rose/climlab/blob/main/docs/source/tutorial.rst)

@AndrewWilliams3142 already has some great material for the tutorial in [this repo](https://github.com/AndrewWilliams3142/ECS_bump/blob/main/notebooks/spectral_lambda.ipynb). We could clean this up and remove the pyrads content for tutorial purposes.

### PR DESCRIPTION
**Pull request by AndrewWilliams3142**
Closes #147 .

@brian-rose I've tried to keep it as straightforward as possible but if you feel there's more you'd like me to explore/add in the notebook then I'm happy to change it :)

### CODE REVIEW

**Comment by brian-rose** [comment]
@AndrewWilliams3142 nice work!

I did some editing:
- make the code look cleaner
- Changed the spectral plots to use bars instead of dots (so we can visualize the spectral intervals in RRTMG). 
- Put your name on the document as original contributor

Please have a look and let me know what you think! We can always roll back any of these changes.

**Comment by brian-rose** [comment]
I switched on the build for PRs on readthedocs.org hoping that we could directly visualize the changes, but unfortunately that doesn't work since the docs just point toward nbviewer, which in turn points toward the main branch of this repo. So you have to pull the changes and open the notebook locally to see it.

**Comment by brian-rose** [comment]
There is at least one scientific issue to consider: when you add water vapor you use `climlab.radiation.water_vapor.FixedRelativeHumidity`. This class sets a fixed RH everywhere. You end up with an unrealistically moist upper troposphere with RH values of 80%.

An alternative is to use `climlab.radiation.water_vapor.ManabeWaterVapor` which uses Manabe's formula (RH decreases linearly with decreasing pressure).

I don't think it would make a huge difference to this demonstration, but good to be aware of.

**Comment by AndrewWilliams3142** [comment]
> @AndrewWilliams3142 nice work!
> 
> I did some editing:
> 
> * make the code look cleaner
> * Changed the spectral plots to use bars instead of dots (so we can visualize the spectral intervals in RRTMG).
> * Put your name on the document as original contributor
> 
> Please have a look and let me know what you think! We can always roll back any of these changes.

Thanks, these look great! I didn't realize that the band widths were also a part of the `wavenumber` axis - that's much neater! I really like the bars for visualizing the spectral intervals, although I think this makes the final plot a bit more difficult to see, and so I've added a section at the end which explains the closing of the window region in terms of the spectral feedback parameter instead of just looking at the OLR curves.

**Comment by AndrewWilliams3142** [comment]
Also just found a typo in the `make_idealized_column` function, (`num_lev` wasn't actually being used) so I've fixed that

**Comment by brian-rose** [comment]
Cool!
I did another round of editing. Mostly I just packaged the model-building code into a function to clean up the code narrative.

But I think there's something funny going on with stratospheric water vapor that gives rise to the strange absorption features at high temperatures. I switched the models over to use ManabeWaterVapor, which ensures that we never have unphysically large specific humidities in the stratosphere. That makes the spectral feedback diagnostics looks a lot more sensible in my opinion.

Take another and let me know what you think (and maybe modify the commentary?). You can easily toggle back and forth between `ManabeWaterVapor` and `FixedRelativeHumidity` in the `calc_olr()` function and switch the whole notebook.

**Comment by AndrewWilliams3142** [comment]
You're right, the `ManabeWaterVapor` is much more realistic. I've just made some minor changes to the text to reflect this.

I'm not sure if this matters much for the notebook, but scientifically I'm a bit confused about why the water vapour window doesn't ever actually "close" when using this specific humidity profile (not shown, but try upping the temperature to ~360K, the feedback in the window region is still quite large).

This might be a problem with just pushing RRTMG outside of its range of validity, not sure. Also most of the idealized studies (e.g., Koll+Cronin 2018, Seeley and Jeevanjee 2020) have used vertically uniform RH profiles, so perhaps this just shows that those results (particularly the fact that the water vapour window closes ~310K in their studies) are dependent on an unrealistic WV profile.

**Comment by brian-rose** [comment]
Ok, I think the notebook is ready to merge. Thanks very much for the valuable contribution!

**Comment by brian-rose** [comment]
> I'm not sure if this matters much for the notebook, but scientifically I'm a bit confused about why the water vapour window doesn't ever actually "close" when using this specific humidity profile (not shown, but try upping the temperature to ~360K, the feedback in the window region is still quite large).
> 
> This might be a problem with just pushing RRTMG outside of its range of validity, not sure. Also most of the idealized studies (e.g., Koll+Cronin 2018, Seeley and Jeevanjee 2020) have used vertically uniform RH profiles, so perhaps this just shows that those results (particularly the fact that the water vapour window closes ~310K in their studies) are dependent on an unrealistic WV profile.

I expect there's a conflation of two different issues here:
1. pushing RRTMG outside of its useful range 
2. sensitivity of the water vapor window to details of the water vapor distribution in upper troposphere / stratosphere.

It would be interesting to test and separate these issues by applying a line-by-line radiation code -- basically revisiting the sensitivity of Koll and Cronin (2018) to water vapor assumptions. Want to work on a paper on this? We'll move that conversation elsewhere.

**Pull request merged**
