### PR TITLE
Readthedocs

### PR DESCRIPTION
**Pull request by cjcardinale**
added:

- readthedocs.yml

- environment.yml

updated the conf.py:

- included readthedocs in the HTML output

- added numpydoc to extensions 

This is in reference to issue #17 .

### CODE REVIEW

**Comment by brian-rose** [comment]
Great, let's see if this works!

**Comment by brian-rose** [comment]
Not quite there yet. The build on Readthedocs failed trying to import extension nbsphinx

**Comment by brian-rose** [comment]
Another missing dependency?

**Comment by cjcardinale** [comment]
I can try adding nbsphinx to the dependencies in environment.yml.  I can also just delete it from the the extensions in conf.py, if it's not needed.  Do I need to fix this issue in another branch and make a new pull request?

**Comment by brian-rose** [comment]
I think you can still make changes to this branch and have them show up here as part of the amended PR. Let's find out.

**Comment by cjcardinale** [comment]
My changes to the branch didn't update here. Maybe it's due to the PR being closed and/or the commits being merged?

**Comment by brian-rose** [comment]
Ok, just submit a new PR.

**Pull request merged**
